apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dummy
  labels:
    app: server-dummy
spec:
  replicas: 1
  selector:
      matchLabels:
        app: server-dummy
  template:
    metadata:
      labels:
        app: server-dummy
    spec:
      containers:
        - name: server
          image: muvaf/server-dummy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-dummy
spec:
  selector:
      app: server-dummy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
